server_id: a-server-id
config:
  prefix: .
  clear_commands: true
channel_groups:
- channels:
  - a-channel-id
  - another-channel-id
  mentions:
    ping:
      reaction:
      - ðŸ‘‹
      response:
      - I see I was pinged.
      - Please just post the issue you are having
      - Or you can gather your logs and post them
    mention:
      reaction:
      - ðŸ‘‹
      response:
      - ""
  commands:
  - command: example
    response:
    - This is the response to the &prefix&example command
  keywords:
  - keyword: example
    reaction:
    - ""
    response:
    - I have responded to seeing the word example.
  regex:
  - pattern: ".*example.*"
    reaction:
    - ""
    response:
    - I have responded to matching the example regex pattern.
  parsing:
    image:
      filetypes:
      - png
      - jpg
    paste:
      sites:
      - name: pastebin
        url: 'https://pastebin.com/'
        format: 'https://pastebin.com/raw/&filename&'
      - name: hastebin
        url: 'https://hastebin.com/'
        format: 'https://hastebin.com/raw/&filename&'
permissions:
- group: admin
filters:
- term: a bad word
  reason:
  - the message was removed because it had 'a bad word' in it
