irc:
  ident: "parkertron" ## The username the bot will use to log in
  email: "" ## The email address the username was registered with. The bot will attempt to register if it's not already
  password: "" ## "changemenow" to not use a password. Note The account can be registered and you can lose it.
  nick: "parkertron" ## The nickanme the bot will display
  real: "Parkertron McBot" ## The Real Name displayed on the server
  prefix: "."
  channels:
    listening: # Channels the bot will join and listen on
      - "pbtg"
  ssl:
    enabled: true
    servername: "irc.freenode.net"
  server: 
    address: "irc.freenode.net"
    port: "6667"
  group: ## user groups. Currently These are not implimented. The Blacklist will ignore specific users
    owner: ""
    admin:
      - 
    mods:
      - 
    blacklist:
-